# Create some default products in the database
# so the user doesn't have to do anything.
unless Product.any?
  Product.create :name => "Nikon D90 Digial Camera", :price => 500.00, :description => "Description of Camera"
  Product.create :name => "Macbook 13 inch", :price => 999.00, :description => "Description of the Macbook 13"
  Product.create :name => "Macbook Air 11 inch", :price => 999.00, :description => "Description of the Macbook Air 11"
  Product.create :name => "Macbook Air 13 inch", :price => 1299.00, :description => "Description of the Macbook Air 13"
  Product.create :name => "Macbook Pro 13 inch", :price => 1299.00, :description => "Description of the Macbook Pro 13"
  Product.create :name => "Macbook Pro 15 inch", :price => 1799.00, :description => "Description of the Macbook Pro 15"
  Product.create :name => "iMac 21.5 inch", :price => 1299.00, :description => "Description of the iMac 21.5 inch"
  Product.create :name => "iMac 27 inch", :price => 1799.00, :description => "Description of the iMac 27 inch"
  Product.create :name => "iPad 2 64GB Wifi+3G", :price => 829.99, :description => "Description of the iPad 2"
  Product.create :name => "iPod Touch 64GB", :price => 829.99, :description => "Description of the iPod Touch"
  Product.create :name => "iPod Shuffle", :price => 49.99, :description => "Description of the iPod Shuffle"
  Product.create :name => "Apple TV", :price => 99.99, :description => "Description of the Apple TV"
  Product.create :name => "iPad 2 Smart Cover", :price => 29.99, :description => "Description of iPad Smart Cover"
  Product.create :name => "iPad 2 Smart Cover - Leather", :price => 59.99, :description => "Description of iPad Smart Cover - Leather"
  Product.create :name => "Amazon Kindle Wi-Fi Only", :price => 139.99, :description => "Description of Kindle Wi-Fi Version"
  Product.create :name => "Amazon Kindle 3G", :price => 139.99, :description => "Description of Kindle 3G Version"
  Product.create :name => "Apple Magic Mouse", :price => 69.00, :description => "Description of Apple Magic Mouse"
  Product.create :name => "Apple Keyboard with Numeric Keypad", :price => 49.00, :description => "Description of Apple Keyboard with Numeric Keypad"
  Product.create :name => "Apple Magic Trackpad", :price => 69.00, :description => "Description of Apple Magic Trackpad"
  Product.create :name => "Airport Extreme Base Station", :price => 179.00, :description => "Description of Airport Extreme Base Station"
  Product.create :name => "Apple Wireless Keyboard", :price => 69.00, :description => "Description of Apple Wireless Keyboard"
  Product.create :name => "Mini DisplayPort to VGA Adapter", :price => 29.00, :description => "Description of Mini DisplayPort to VGA Adapter"
  Product.create :name => "Mini DisplayPort to DVI Adapter", :price => 29.00, :description => "Description of Mini DisplayPort to DVI Adapter"
  Product.create :name => "Mini DVI to VGA Adapter", :price => 29.00, :description => "Description of Mini DVI to VGA Adapter"
  Product.create :name => "DVI to VGA Adapter", :price => 29.00, :description => "Description of DVI to VGA Adapter"
  Product.create :name => "Canon Rebel XS Kit (Black)", :price => 549.95, :description => "Description of Canon Rebel XS Kit (Black)"
  Product.create :name => "AirPort Express Base Station", :price => 99.00, :description => "Description of AirPort Express Base Station"
  Product.create :name => "Time Capsule - 1TB", :price => 299.00, :description => "Description of Time Capsule - 1TB"
  Product.create :name => "Time Capsule - 2TB", :price => 499.00, :description => "Description of Time Capsule - 2TB"

end